---
- name: Deploy nirvana_pc to my server
  hosts: na-prod
  vars:
    ansistrano_deploy_from: ./dist
    ansistrano_deploy_to: /mnt/www/yt_pc/
    ansistrano_keep_releases: 10
    # There seems to be an issue with rsync in vagrant
    ansistrano_deploy_via: rsync
  user: deploy
  roles:
    - { role: carlosbuenosvinos.ansistrano-deploy }
  tasks:
    - name: restart nginx after deploy
      shell: sudo service nginx reload
