---
- name: Rollback nirvana_pc to my server
  hosts: frontservers
  vars:
    ansistrano_deploy_to: mnt/www/nirvana_pc/
  user: deploy
  roles:
    - { role: carlosbuenosvinos.ansistrano-rollback }
  tasks:
    - name: restart nginx after rollback
      shell: sudo service nginx restart
